// server/scripts/seedQuestions.js
require('dotenv').config({ path: require('path').resolve(__dirname, '../.env') });
const connectDB = require('../src/config/db');
const Question = require('../src/models/Question');

const docs = [
  /* --------------------------- APTITUDE (20) --------------------------- */
  {
    text: "What is 12 + 23?",
    options: ["33", "35", "36", "37"],
    correctIndex: 1,
    explanation: "12 + 23 = 35.",
    category: "Aptitude",
    difficulty: "Easy",
  },
  {
    text: "If A:B = 2:3 and B:C = 4:5, find A:C?",
    options: ["8:15", "3:2", "2:5", "5:8"],
    correctIndex: 0,
    explanation: "A:C = 2×4 : 3×5 = 8:15.",
    category: "Aptitude",
    difficulty: "Medium",
  },
  {
    text: "A train running at 72 km/hr crosses a pole in 20 seconds. What is the length of the train?",
    options: ["360 m", "400 m", "420 m", "450 m"],
    correctIndex: 1,
    explanation: "72 km/hr = 20 m/s → distance = 20×20 = 400 m.",
    category: "Aptitude",
    difficulty: "Easy",
  },
  {
    text: "If 5 workers complete a job in 12 days, how many days will 8 workers take?",
    options: ["7.5 days", "8 days", "9 days", "10 days"],
    correctIndex: 0,
    explanation: "Work ∝ workers → Time = 12×(5/8) = 7.5 days.",
    category: "Aptitude",
    difficulty: "Easy",
  },
  {
    text: "What is the median of 3, 7, 9, 10, 15?",
    options: ["7", "9", "10", "8"],
    correctIndex: 1,
    explanation: "The middle number is 9.",
    category: "Aptitude",
    difficulty: "Easy",
  },
  {
    text: "A shopkeeper gives 20% discount on marked price and still gains 20%. Relation between M and C?",
    options: ["M = 1.5C", "M = 1.2C", "M = 1.8C", "M = 2C"],
    correctIndex: 0,
    explanation: "SP = 1.2C, SP = 0.8M → M = 1.5C.",
    category: "Aptitude",
    difficulty: "Medium",
  },
  {
    text: "The probability of event A is 1/3 and event B is 1/4 (independent). Probability that both occur?",
    options: ["1/7", "1/12", "1/6", "1/4"],
    correctIndex: 1,
    explanation: "P(A∩B) = 1/3 × 1/4 = 1/12.",
    category: "Aptitude",
    difficulty: "Easy",
  },
  {
    text: "Average of five consecutive even numbers is 26. Largest number?",
    options: ["30", "28", "32", "34"],
    correctIndex: 0,
    explanation: "Numbers: 22, 24, 26, 28, 30 → largest = 30.",
    category: "Aptitude",
    difficulty: "Easy",
  },
  {
    text: "Sum of first n natural numbers is 210. Find n.",
    options: ["19", "20", "21", "22"],
    correctIndex: 1,
    explanation: "n(n+1)/2 = 210 → n = 20.",
    category: "Aptitude",
    difficulty: "Medium",
  },
  {
    text: "If a number is increased by 25% and then decreased by 20%, net change is?",
    options: ["0%", "+5%", "+10%", "-5%"],
    correctIndex: 0,
    explanation: "1.25 × 0.8 = 1 → net 0% change.",
    category: "Aptitude",
    difficulty: "Easy",
  },
  {
    text: "If ratio of ages of A:B is 3:4, after 6 years ratio = 4:5. Present age of A?",
    options: ["12", "15", "18", "20"],
    correctIndex: 2,
    explanation: "Let 3x,4x. (3x+6)/(4x+6)=4/5 → x=6 → A = 18.",
    category: "Aptitude",
    difficulty: "Medium",
  },
  {
    text: "If circumference of a circle is 31.4 cm, find radius (π = 3.14).",
    options: ["5 cm", "10 cm", "15 cm", "3 cm"],
    correctIndex: 0,
    explanation: "r = 31.4 / (2×3.14) = 5 cm.",
    category: "Aptitude",
    difficulty: "Easy",
  },
  {
    text: "What is the 10th term of AP: 3, 7, 11, ...?",
    options: ["39", "40", "43", "47"],
    correctIndex: 0,
    explanation: "a_n = 3 + (n−1)×4 → a_10 = 39.",
    category: "Aptitude",
    difficulty: "Easy",
  },
  {
    text: "Two pipes A & B fill a tank in 10 and 15 hrs. A runs 2 hrs, then B joins. Time left?",
    options: ["4 hrs", "5 hrs", "6 hrs", "7 hrs"],
    correctIndex: 1,
    explanation: "A fills 1/10 per hr → after 2 hrs, remaining = 4/5. A+B = 1/6 per hr → (4/5)/(1/6) ≈ 4.8 ≈ 5 hrs.",
    category: "Aptitude",
    difficulty: "Medium",
  },
  {
    text: "If 4 men build a wall in 12 days, men required for 8 days?",
    options: ["4", "6", "8", "10"],
    correctIndex: 1,
    explanation: "Men = 4×(12/8) = 6.",
    category: "Aptitude",
    difficulty: "Easy",
  },
  {
    text: "In a class, 60% passed in Maths, 50% in English, 30% in both. At least one?",
    options: ["80%", "70%", "60%", "90%"],
    correctIndex: 0,
    explanation: "P(A∪B) = 60 + 50 − 30 = 80%.",
    category: "Aptitude",
    difficulty: "Easy",
  },
  {
    text: "Item costs 120 after 20% discount. Marked price?",
    options: ["140", "150", "160", "180"],
    correctIndex: 1,
    explanation: "Marked = 120 / 0.8 = 150.",
    category: "Aptitude",
    difficulty: "Easy",
  },
  {
    text: "A bag has 3 red and 2 blue balls. Probability of red?",
    options: ["1/5", "2/5", "3/5", "4/5"],
    correctIndex: 2,
    explanation: "3 red out of 5 → 3/5.",
    category: "Aptitude",
    difficulty: "Easy",
  },
  {
    text: "Perimeter of square is 48 cm. Area?",
    options: ["144 cm²", "196 cm²", "64 cm²", "256 cm²"],
    correctIndex: 0,
    explanation: "Side = 48/4 = 12 → Area = 12² = 144 cm².",
    category: "Aptitude",
    difficulty: "Easy",
  },
  {
    text: "If cost price = 80, selling price = 100. Find profit %.",
    options: ["10%", "20%", "25%", "30%"],
    correctIndex: 2,
    explanation: "(Profit/CP)*100 = (20/80)*100 = 25%.",
    category: "Aptitude",
    difficulty: "Easy",
  },

  /* --------------------------- CODING (20) --------------------------- */
  {
    text: "Time complexity of Binary Search?",
    options: ["O(1)", "O(n)", "O(log n)", "O(n log n)"],
    correctIndex: 2,
    explanation: "Binary Search halves each step → O(log n).",
    category: "Coding",
    difficulty: "Easy",
  },
  {
    text: "Which uses FIFO?",
    options: ["Stack", "Queue", "Tree", "Heap"],
    correctIndex: 1,
    explanation: "Queue uses FIFO.",
    category: "Coding",
    difficulty: "Easy",
  },
  {
    text: "Traversal order Left-Root-Right?",
    options: ["Preorder", "Inorder", "Postorder", "Level Order"],
    correctIndex: 1,
    explanation: "Inorder = Left Root Right.",
    category: "Coding",
    difficulty: "Easy",
  },
  {
    text: "Output of print(2**3**2) in Python?",
    options: ["64", "512", "256", "8"],
    correctIndex: 1,
    explanation: "Exponentiation is right-associative → 2**(3**2) = 512.",
    category: "Coding",
    difficulty: "Medium",
  },
  {
    text: "Stable sorting algorithm?",
    options: ["QuickSort", "HeapSort", "MergeSort", "SelectionSort"],
    correctIndex: 2,
    explanation: "MergeSort is stable.",
    category: "Coding",
    difficulty: "Medium",
  },
  {
    text: "Data structure for recursion call tracking?",
    options: ["Queue", "Stack", "Linked List", "Array"],
    correctIndex: 1,
    explanation: "Call stack follows LIFO.",
    category: "Coding",
    difficulty: "Easy",
  },
  {
    text: "Algorithmic technique for 0/1 Knapsack?",
    options: ["Greedy", "Dynamic Programming", "Divide & Conquer", "Backtracking"],
    correctIndex: 1,
    explanation: "0/1 Knapsack → Dynamic Programming.",
    category: "Coding",
    difficulty: "Medium",
  },
  {
    text: "Worst case of QuickSort?",
    options: ["O(n log n)", "O(n²)", "O(n)", "O(log n)"],
    correctIndex: 1,
    explanation: "Poor pivot choice gives O(n²).",
    category: "Coding",
    difficulty: "Medium",
  },
  {
    text: "Hash collision resolution 'Chaining' means?",
    options: [
      "Store collided items in same bucket list",
      "Move item to next slot",
      "Rehash table",
      "Double hashing",
    ],
    correctIndex: 0,
    explanation: "Chaining uses a list per bucket.",
    category: "Coding",
    difficulty: "Easy",
  },
  {
    text: "Characteristic of AVL tree?",
    options: [
      "All leaves same level",
      "Height O(log n)",
      "Two children always",
      "Inorder = preorder",
    ],
    correctIndex: 1,
    explanation: "AVL keeps height balanced → O(log n) height.",
    category: "Coding",
    difficulty: "Medium",
  },
  {
    text: "Output of print(''.join(sorted('cba')))?",
    options: ["cba", "abc", "bac", "acb"],
    correctIndex: 1,
    explanation: "sorted returns ['a','b','c'] → 'abc'.",
    category: "Coding",
    difficulty: "Easy",
  },
  {
    text: "Which is NOT a use of Trie?",
    options: [
      "Autocomplete",
      "IP routing",
      "Spell check",
      "Sorting numbers by value",
    ],
    correctIndex: 3,
    explanation: "Tries handle prefix data, not numeric sorting.",
    category: "Coding",
    difficulty: "Medium",
  },
  {
    text: "Which heap operation takes O(log n)?",
    options: ["Find max", "Insert", "Build heap", "Find min"],
    correctIndex: 1,
    explanation: "Insert requires bubble-up → O(log n).",
    category: "Coding",
    difficulty: "Easy",
  },
  {
    text: "Technique that saves results of overlapping subproblems?",
    options: ["Memoization", "Tail recursion", "Backtracking", "Greedy"],
    correctIndex: 0,
    explanation: "Memoization stores computed results.",
    category: "Coding",
    difficulty: "Easy",
  },
  {
    text: "Which grows fastest for large n?",
    options: ["n log n", "n²", "n³", "2ⁿ"],
    correctIndex: 3,
    explanation: "Exponential 2ⁿ grows fastest.",
    category: "Coding",
    difficulty: "Medium",
  },
  {
    text: "Shortest path (non-negative weights)?",
    options: ["Bellman-Ford", "Dijkstra", "Floyd-Warshall", "Kruskal"],
    correctIndex: 1,
    explanation: "Dijkstra handles non-negative weights.",
    category: "Coding",
    difficulty: "Medium",
  },
  {
    text: "typeof NaN in JS?",
    options: ['"number"', '"NaN"', '"object"', '"undefined"'],
    correctIndex: 0,
    explanation: 'typeof NaN returns "number".',
    category: "Coding",
    difficulty: "Easy",
  },
  {
    text: "What does BFS use internally?",
    options: ["Stack", "Queue", "Priority Queue", "Tree"],
    correctIndex: 1,
    explanation: "BFS uses a queue.",
    category: "Coding",
    difficulty: "Easy",
  },
  {
    text: "Which data structure gives O(1) average lookup?",
    options: ["Array", "Hash Table", "Tree", "Queue"],
    correctIndex: 1,
    explanation: "Hash Table average O(1).",
    category: "Coding",
    difficulty: "Easy",
  },
  {
    text: "Tail recursion optimization does what?",
    options: [
      "Reuses stack frame",
      "Removes base case",
      "Runs parallel calls",
      "Caches results",
    ],
    correctIndex: 0,
    explanation: "Tail recursion reuses same stack frame.",
    category: "Coding",
    difficulty: "Hard",
  },

  /* --------------------------- VERBAL (20) --------------------------- */
  {
    text: "Synonym of 'abundant'?",
    options: ["Scarce", "Plentiful", "Tiny", "Sparse"],
    correctIndex: 1,
    explanation: "'Plentiful' means abundant.",
    category: "Verbal",
    difficulty: "Easy",
  },
  {
    text: "Correct sentence?",
    options: [
      "He don't know the answer.",
      "He doesn't knows the answer.",
      "He doesn't know the answer.",
      "He aren't knowing the answer.",
    ],
    correctIndex: 2,
    explanation: "Correct: He doesn't know the answer.",
    category: "Verbal",
    difficulty: "Easy",
  },
  {
    text: "Antonym of 'mitigate'?",
    options: ["Alleviate", "Intensify", "Soothe", "Calm"],
    correctIndex: 1,
    explanation: "'Intensify' is opposite of mitigate.",
    category: "Verbal",
    difficulty: "Medium",
  },
  {
    text: "River is to water as road is to ___?",
    options: ["Car", "Asphalt", "Traffic", "Path"],
    correctIndex: 3,
    explanation: "Road relates to path.",
    category: "Verbal",
    difficulty: "Easy",
  },
  {
    text: "The committee reached a ______ about the policy.",
    options: ["Conscience", "Consensus", "Conscious", "Consent"],
    correctIndex: 1,
    explanation: "The correct word is 'consensus'.",
    category: "Verbal",
    difficulty: "Easy",
  },
  {
    text: "Sentence with correct punctuation?",
    options: [
      "Lets eat, grandma.",
      "Let's eat grandma.",
      "Lets eat grandma.",
      "Let's eat, grandma.",
    ],
    correctIndex: 3,
    explanation: "Correct: Let's eat, grandma.",
    category: "Verbal",
    difficulty: "Medium",
  },
  {
    text: "Meaning of 'ephemeral'?",
    options: ["Eternal", "Transient", "Long-lasting", "Infinite"],
    correctIndex: 1,
    explanation: "Ephemeral = short-lived, transient.",
    category: "Verbal",
    difficulty: "Medium",
  },
  {
    text: "She sang beautifully — 'beautifully' is what part of speech?",
    options: ["Noun", "Verb", "Adverb", "Adjective"],
    correctIndex: 2,
    explanation: "'Beautifully' modifies verb → Adverb.",
    category: "Verbal",
    difficulty: "Easy",
  },
  {
    text: "Passive voice: which sentence?",
    options: [
      "The chef cooked the meal.",
      "The meal was cooked by the chef.",
      "The chef is cooking the meal.",
      "They will cook the meal.",
    ],
    correctIndex: 1,
    explanation: "Passive: The meal was cooked by the chef.",
    category: "Verbal",
    difficulty: "Easy",
  },
  {
    text: "Correct spelling?",
    options: ["Accommodate", "Acommodate", "Accomodate", "Acomodate"],
    correctIndex: 0,
    explanation: "Correct: Accommodate.",
    category: "Verbal",
    difficulty: "Easy",
  },
  {
    text: "Had I known, I _____ told you.",
    options: ["would have", "would", "will have", "had"],
    correctIndex: 0,
    explanation: "Correct: would have told you.",
    category: "Verbal",
    difficulty: "Medium",
  },
  {
    text: "Parallel structure?",
    options: [
      "She likes singing, to dance, and to paint.",
      "She likes singing, dancing, and painting.",
      "She likes to sing, dancing, and to paint.",
      "She likes singing, dancing, and to paint.",
    ],
    correctIndex: 1,
    explanation: "Parallel gerund forms.",
    category: "Verbal",
    difficulty: "Medium",
  },
  {
    text: "He showed great ______ in handling the crisis.",
    options: ["temper", "composure", "fury", "rage"],
    correctIndex: 1,
    explanation: "'Composure' fits best.",
    category: "Verbal",
    difficulty: "Medium",
  },
  {
    text: "Bird is to flock as fish is to ___?",
    options: ["Card", "School", "Herd", "Pack"],
    correctIndex: 1,
    explanation: "Group of fish = school.",
    category: "Verbal",
    difficulty: "Easy",
  },
  {
    text: "The project was delayed. ___, the team submitted it late.",
    options: ["Therefore", "However", "Consequently", "Meanwhile"],
    correctIndex: 2,
    explanation: "'Consequently' shows result.",
    category: "Verbal",
    difficulty: "Medium",
  },
  {
    text: "'She sells seashells by the seashore' is an example of:",
    options: ["Alliteration", "Metaphor", "Simile", "Hyperbole"],
    correctIndex: 0,
    explanation: "Repetition of sound = Alliteration.",
    category: "Verbal",
    difficulty: "Easy",
  },
  {
    text: "Best revision for clarity: 'The results, which were unexpected, surprised the team.'",
    options: [
      "The results surprised the team.",
      "The unexpected results surprised the team.",
      "Results were surprising to the team.",
      "The team was surprised by results.",
    ],
    correctIndex: 1,
    explanation: "'The unexpected results surprised the team.' is concise.",
    category: "Verbal",
    difficulty: "Medium",
  },
  {
    text: "Antonym of 'augment'?",
    options: ["Increase", "Reduce", "Amplify", "Enhance"],
    correctIndex: 1,
    explanation: "Augment means increase → antonym reduce.",
    category: "Verbal",
    difficulty: "Easy",
  },
  {
    text: "Her argument was _____, convincing even critics.",
    options: ["tenuous", "compelling", "vague", "irrelevant"],
    correctIndex: 1,
    explanation: "'Compelling' means persuasive.",
    category: "Verbal",
    difficulty: "Medium",
  },
];

async function seed() {
  if (!process.env.MONGO_URI) {
    console.error("MONGO_URI missing in .env");
    process.exit(1);
  }
  await connectDB(process.env.MONGO_URI);
  // WARNING: this removes all documents from the Question collection
  await Question.deleteMany({});
  const inserted = await Question.insertMany(docs);
  console.log(`✅ Inserted ${inserted.length} questions successfully.`);
  process.exit(0);
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
